version: 3
service:
        nginx:
                image:
                   build: ./
                   volume: 
                       - source=/home/ubuntu/Dockerexample/folde 
                       - target=/usr/share/nginx/html
                   ports:
                           - 8081:80      

